package org.ccci.obiee.client.init;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebServiceClient;

import com.google.common.base.Throwables;

public class ServiceFactory
{
    public <T extends Service> T buildService(Class<T> serviceClass)
    {
        return construct(serviceClass);
    }

    private <T> T construct(Class<T> serviceClass)
    {
        Constructor<T> constructor;
        try
        {
            constructor = serviceClass.getConstructor();
        }
        catch (NoSuchMethodException e)
        {
            throw new RuntimeException("can't find default service constructor.  Was the service class generated by the JAX-WS RI?", e);
        }
        try
        {
            return constructor.newInstance();
        }
        catch (InstantiationException e)
        {
            throw Throwables.propagate(e);
        }
        catch (IllegalAccessException e)
        {
            throw Throwables.propagate(e);
        }
        catch (InvocationTargetException e)
        {
            throw Throwables.propagate(e.getCause());
        }
    }
}
